version: "2"
services:
  nginx:
    image: nginx:1.18.0
    pid: "host"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt/live/fullchain.pem:/etc/fullchain.pem
      - /etc/letsencrypt/live/fullchain.pem:/etc/privkey.pem
      - /var/log/nginx:/var/log/nginx
      - ./nginx.conf:/etc/nginx/nginx.conf
    environment:
      - SSLPATH=neocompiler.io-0001  
