version: "2"
services:
  nginx:
    image: nginx:1.18.0
    pid: "host"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - $LOCAL_SSL_PATH_LIVE/fullchain.pem:/etc/fullchain.pem
      - $LOCAL_SSL_PATH_LIVE/privkey.pem:/etc/privkey.pem
      - /var/log/nginx:/var/log/nginx
      - ./nginx.conf:/etc/nginx/nginx.conf
