version: "2"
services:
  nginx:
    build: ./DockerNginx/
    pid: "host"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/log/nginx:/var/log/nginx

